<?php include_once('includes/db.php');?>
<?php include_once('includes/functions.php');
session_start();?>
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<title>Details List</title>

	<!-- Google Font -->
	<link href='https://fonts.googleapis.com/css?family=Roboto+Slab:100,300,700,400' rel='stylesheet' type='text/css'>

	<!-- Library CSS -->
	<link rel="stylesheet" href="css/library/font-awesome.min.css">
        <link rel="stylesheet" href="css/library/font-awesome.css">
	<link rel="stylesheet" href="css/library/bootstrap.min.css">
	<link rel="stylesheet" href="css/library/owl.carousel.css">
	<link rel="stylesheet" href="css/library/font-awesome.min.css">
	<link rel="stylesheet" href="css/library/jquery-ui.min.css">
	<link rel="stylesheet" href="css/library/jquery.fancybox.css">
	
	<!-- MAIN STYLE -->
	<!-- MAIN STYLE -->
	<link rel="stylesheet" href="css/style.css"><link rel="shortcut icon" href="https://www.littlefashions.in/images/favicon.png">
<link rel="stylesheet" href="css/color-pink.css">
    <script>
		$(function(){
 var shrinkHeader = 300;
  $(window).scroll(function() {
    var scroll = getCurrentScroll();
      if ( scroll >= shrinkHeader ) {
           $('.header').addClass('shrink');
        }
        else {
            $('.header').removeClass('shrink');
        }
  });
function getCurrentScroll() {
    return window.pageYOffset || document.documentElement.scrollTop;
    }
});
    </script>
</head>
<body>

	<!-- LOADING -->
	<div class="loading-container" id="loading">
		<div class="loading-inner">
			<span class="loading-1"></span>
			<span class="loading-2"></span>
			<span class="loading-3"></span>
		</div>
	</div>
	<!-- END LOADING -->

	<div class="wrap-page">

		<!-- HEADER -->
					<nav class="navigation_top ">
						<?php include_once('top.php');?>
					</nav>		
         			<header class="header _1">
                    	<?php include_once('header.php');?>
                    </header>
                    <header class="header _1">
                    	<?php include_once('menu.php');?>
					</header>
		<!-- PRODUCT GRID -->
		<section class="product-grid">
			<div class="container">
				<div class="row">
					<div class="col-md-12">



						<!-- GRID CONTENT -->
						<div class="grid-cn-1">
                <div class="row">
                <div class="heading _1 text-center margin_t_15">
        
                    <h2 class="text-uppercase">Terms of Use</h2>
        
                </div>
                <div class="col-md-12">
                	<p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
</p>
<p>Please read the following terms and conditions very carefully as your use of service is subject to your acceptance of and compliance with the following terms and conditions.
</p>




<h3>Contents</h3>
<p>1. General Information </p>
<p>2. Account and Registration</p> 
<p>3. Pricing, Promotions & Coupon Codes</p> 
<p>4. Transactions & Cancellation</p>  
<p>5. User Conduct </p>
<p>6. Shop 'n' Earn Loyalty Cash</p>  
<p>8. Other Terms </p>

<h3>General Information</h3>
<p>The domain name www.littlefashion.in (hereinafter referred to as "Website") is registered in the name of Little Fashion, a company incorporated under the Companies Act, 1956 . </p>
<p>Your use of the Website and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Website. If you transact on the Website, You shall be subject to the policies that are applicable to the Website for such transaction. For the purpose of these Terms of Use, wherever the context so requires ‘You’ or "User" shall mean any natural or legal person who has agreed to become a member of the Website by providing Registration Data while registering on the Website as Registered User using the computer systems. The term "we", "us", "our" shall mean BNJ or littlefashion.in or all.</p>
<p>ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS IN THIS AGREEMENT, SO PLEASE READ THIS AGREEMENT CAREFULLY BEFORE PROCEEDING.</p>
<p>All products/services and information displayed on littlefashion.in constitute an "invitation to offer". Your order for purchase constitutes your "offer" which shall be subject to the terms and conditions as listed below. littlefashion.in reserves the right to accept or reject your offer. If you have supplied us with your valid email address, we will notify you by email as soon as possible to confirm receipt of your order and email you again to confirm details and therefore process the order. Our acceptance of your order will take place upon dispatch of the product(s) ordered. No act or omission of littlefashion.in prior to the actual dispatch of the product(s) ordered will constitute acceptance of your offer. </p>
<h3>Membership Eligibility</h3>
<p>Use of the Site is available only to persons who can form legally binding contracts under applicable law. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the Site. You may use this site only if your age is over 18 years. </p>
<p>littlefashion.in reserves the right to terminate your membership and refuse to provide you with access to the Site if littlefashion.in discovers that you are under the age of 18 years. In case of a business entity, you represent that you have the necessary authority to bind the entity to this User Agreement. Unless otherwise specified, the materials on this website are directed solely at those who access this website from India. littlefashion.in makes no representation that any products or services referred to in the materials on this website are appropriate for use, or available outside India. Those who choose to access this Site from outside India are responsible for compliance with local laws if and to the extent local laws are applicable. littlefashion.in will deliver the products only within India and will not be liable for any claims relating to any products ordered from outside India. </p>
<p>Unless otherwise stated as additional terms and conditions which are product specific, these terms and conditions supersede all previous representations, understandings, or agreements and shall prevail notwithstanding any variance with any other terms of any order submitted. By using the services of littlefashion.in you agree to be bound by the Terms and Conditions. </p>
<h3>Modifications</h3>
<p>littlefashion.in reserves the right at all times to discontinue or modify the Terms of Use and/or our Privacy Policy as we deem necessary or desirable without any prior notification. Such changes may include, among other things, the adding of certain fees and charges. Any such modifications would be effective immediately. We suggest that you read our Terms and Conditions and Privacy policy from time to time to stay informed. Any use of the site after such modifications would be deemed to constitute acceptance of the modified terms by the End User.</p>
<h3>Account and Registration</h3>
<p>It is the user’s responsibility to keep the details of the account and password confidential and you agree to accept responsibility for all activities that occur under Your Account or Password. littlefashion.in shall not be liable to any person for any loss or damage which may arise as a result of any failure by the user to protect the account details or the password. In case of any suspected breach please contact us immediately. If littlefashion.in has reason to believe that there is likely to be a breach of security or misuse of the littlefashion.in Site, we may require you to change your password or we may suspend your account without any liability to littlefashion.in. </p><br>

<h3>You also agree to:</h3>

<p>1. Provide true, accurate, current and complete information about yourself as prompted by littlefashion website during the registration process (such information being the "Registration Data")</p>
<p>2. Maintain and promptly update the Registration Data to keep it true, accurate, current and complete. If you provide any information that is untrue, inaccurate, incomplete, or not current or if littlefashion.in has reasonable grounds to suspect that such information is untrue, inaccurate, not current or not in accordance with the User Agreement, littlefashion.in will have the right to indefinitely suspend or terminate your membership and refuse to provide you with access to the Site.</p><br>


<h3> Pricing, Promotions & Coupon Codes</h3>
<p>Pricing Information</p>
<p>While littlefashion.in shall endeavour to provide accurate product and pricing information, yet typographical errors might occur. littlefashion.in cannot confirm the price of a product until after you order. In the event that a product is listed at an incorrect price or with incorrect information due to an error in pricing or product information, littlefashion.in shall have the right, at our sole discretion, to refuse or cancel any orders placed for that product, unless the product has already been dispatched. In the event that an item is mis-priced, littlefashion.in may, at its discretion, either contact you for instructions or cancel your order and notify you of such cancellation. Unless the product ordered by you has been dispatched, your offer will not be deemed accepted and littlefashion.in will have the right to modify the price of the product and contact you for further instructions using the e-mail address provided by you during the time of registration, or cancel the order and notify you of such cancellation. In the event that littlefashion.in accepts your order the same shall be debited to your credit card account and duly notified to you by email that the payment has been processed. The payment may be processed prior to littlefashion.in dispatch of the product that you have ordered. If we have to cancel the order after we have processed the payment, the said amount will be reversed back to your credit card account. </p>
<p>Promotion Offers</p>
<p>For any returned or undelivered orders, partial or whole, the user will not be eligible to avail of the offer used to purchase the original order. The benefit of the offer would also not be included in the refund provided. If the product(s) returned are part of any free offer, Eg: Buy 2 get 1 free or Buy 1 get 1 free, all the products related to the offer would have to be returned by you, as they have been purchased as part of a group offer. The refund/replacement process would only be initiated once all the products have been returned. </p>
<p>From time to time, we may provide a free sample or gift along with our orders which are eligible for the offer. These samples/gifts will not be eligible for return/replacement/refund under any circumstances.</p>
<p>Coupon Codes & Cart Offers</p>
<p>To offer special discounts to our users from time to time, we share coupon codes based discounts. To prevent any possible misuses we have put in place a few checks on the ways in which these coupon codes can be used. </p>
To make the best use of the coupon code offers, please go through the following terms and conditions applicable on all coupon codes</p>

<p>1. Coupon Codes & Cart Offers based offer will be valid upon application of the coupon code at the time of placing order.</p>
<p>2. Coupon Codes & Cart Offers will be valid till the date communicated or till stocks last on the applicable products, whichever happens earlier.</p>
<p>3. Coupon Codes & Cart Offers will not be valid on  Combos,Bottle Cleaning & Sterilization, Bottles & Accessories unless otherwise mentioned.</p>
<p>5. A Coupon Codes & Cart Offers cannot be clubbed with any other coupon code or with any other offer including offers running on the site without using coupons.</p>
<p>6. A coupon will provide the stated discount of the coupon code or the discount already stated on the product whichever is higher unless otherwise mentioned.</p>
<p>7. Coupon codes shared individually with a user will be applicable on purchase made by that particular user only.</p>
<p>8. The website reserves the right to change the terms and conditions of any coupon code any time without prior intimation.</p>
<p>9. Shipping / Cash on delivery rules and charges apply on the net amount payable upon application of the coupon code unless otherwise mentioned.</p>
<p>10. Cashback coupons are valid for next purchase as per the conditions mentioned with the Cashback offer.
<p>11. The Cash Coupons added to an account can be changed/updated at any point of time by Babysnjoy LLP without any prior intimation. These changes could be made from time to time even before the valid expiry date of the existing Cash Coupons.</p>

<p>Cashback Offers</p>
<p>Cashback Offers are run from time to time to award users for their purchase from littlefashion.in. The terms and conditions applicable with these Cashback offers are as below </p>
<p>• The Cashback amount, the purchase conditions and the product range on which the Cashback offer is valid will be as specified along with the Cashback offer</p>
<p>• The Cashback amount will be received by the user as a coupon through a Cashback email. The Cashback coupon would be received by you up to 10 days after the delivery of the order. Eg: If your order has been delivered on 3rd September, you would be receiving the Cashback coupon on mail latest by 13th September.</p>
<p>• Cashback will not be earned on purchases from the categories Bottles & Accessories, Bottle Cleaning & Sterilization or on purchasing any of the Guaranteed Savings Offer codes. They will only be earned on the products mentioned in the cashback promotions.</p>
<p>• Cashback will not be provided for any product(s) which have either not been delivered to you or which has been returned by you. In the event of any replacement provided to you, the replacement product value will not be added to the cashback calculations available to you to redeem on site.</p>
<p>• Redemption of the Cashback coupon will not be applicable on Combos, Bottle Cleaning & Sterilization, Bottles & Accessories unless otherwise mentioned.</p>
<p>• The maximum Cashback given out is Rs. 250 and is applicable on the MRP of the product, unless mentioned otherwise</p>
<p>• The Cashback coupon can be used till the date of validity as specified in the Cashback email</p>
<p>• The company reserves the right to change the terms and conditions of the Cashback offers without prior intimation</p>
<p>• The Cashback is not applicable on cancelled orders</p>
<h3>Transactions & Cancellations</h3>
<p>Credit Card Details</p>
<p>You hereby agree, understand and confirm that the credit card details provided by you for availing of services on website will be correct, accurate and current. Under no circumstances you shall use a credit card which is not lawfully owned by you. You further agree and undertake to provide the correct and valid credit card details to us. The card details will not be utilised and shared by us with any of the third parties unless required for fraud verifications or by law, regulation or court order. We will not be liable for any credit card fraud. The liability for use of a card fraudulently will be on you and the onus to 'prove it otherwise' shall be exclusively on you. </p>

<p>Fraudulent /Declined Transactions</p>
<p>In case of fraudulent use of the site, we reserve the right to recover the cost of goods, collection charges and lawyers fees from person(s) concerned. We reserve the right to initiate legal proceedings against such person(s) for fraudulent use of the Site and any other unlawful acts or acts or omissions in breach of these terms and conditions.</p> 

<p>Cancellations by the Customer</p>
<p>In case we receive a cancellation notice and the order has not been shipped by us, we shall cancel the order and refund the entire amount. The orders that have already been shipped out by us will not be cancelled and you will have to check our return policy on those orders.</p> 
<p>Cancellation by littlefashion.in</p>
<p>Under certain circumstances it might not be possible for us to accept an order and we may be compelled to cancel the same. We reserve the right to refuse or cancel any order for any reason at our sole discretion. Some situations that may result in your order being cancelled include limitations on quantities available for purchase, inaccuracies or errors in product or pricing information, or problems identified by our credit and fraud avoidance department. We may also ask for additional verifications or information before accepting any order. We will contact you if all or any portion of your order is cancelled or if additional information is required to accept your order. If your order is cancelled after your credit card has been charged, the said amount will be reversed back in your Card Account. The customer agrees not to dispute the decision made by us and accept our decision regarding the cancellation.</p>
<p>Payment</p>
<p>While availing any of the payment method/s offered by us, we are not responsible or take no liability of whatsoever nature in respect of any loss or damage arising directly or indirectly to you out of the decline due to: </p>
<p>1. lack of authorization for any transaction/s,</p> 
<p>2. or exceeding the preset limit mutually agreed by you and between your "Bank/s", </p>
<p>3. or any payment issues arising out of the transaction,</p>
<p>4. or decline of transaction for any other reason/s. </p>
<p>All payments made against the purchases/services on littlefashion.in by you shall be compulsorily in Indian Rupees acceptable by the Union of India. littlefashion.in does not accept any other form of currency with respect to the purchases.
Before shipping your order to you, we may request you to provide supporting documents (including but not limited to Govt. issued ID and address proof) to establish the ownership of the payment instrument used by you for your purchase. This is done in the interest of providing a safe online shopping environment to our users.</p><br>

<h3>User Conduct</h3>
<p>You Agree and Confirm</p>
<p>1. That you will use the services provided by littlefashion.in, its affiliates, consultants and contracted companies, for lawful purposes only and comply with all applicable laws and regulations while using the Site and transacting on the Site. </p>
<p>2. You will provide true, accurate, complete and current information in all instances where such information is requested of you. littlefashion.in reserves the right to confirm and validate the information and other details provided by you at any point of time. If upon confirmation your details are found not to be true (wholly or partly), littlefashion.in has the right in its sole discretion to reject the registration and debar you from using the Services of littlefashion.in and / or other affiliated websites without prior intimation whatsoever.</p> 
<p>3. To compensate littlefashion.in for any extra cost incurred for redelivery in the event of a non-delivery in the first instance on account of a mistake by you (i.e. wrong name or address or any other wrong information).</p> 
<p>4. That you using your best and prudent judgment before entering into any transaction through this Site doing so at your sole risk. </p>
<p>5. After placing an order for a product you agree to be bound by the conditions of sale included in the item's description. 
You may not use the Site for any of the following purposes:</p>
<p>1. Disseminating any unlawful, harassing, libellous, abusive, threatening, harmful, vulgar, obscene, or otherwise objectionable material. </p>
<p>2. Transmitting material that encourages conduct that results in civil liability or otherwise breaches any relevant laws, regulations or code of practice or constitutes a criminal offence.</p> 
<p>3. Gaining unauthorised access to other computer systems. </p>
<p>4. Interfering with any other person's use or enjoyment of the Site.</p> 
<p>5. Breaching any applicable laws.</p> 
<p>6. Interfering or disrupting networks or web sites connected to the Site.</p> 
<p>7. Making, transmitting or storing electronic copies of materials protected by copyright without the permission of the owner. Design details and Colours. </p>
<p>We have made every effort to capture high resolution images of our products so that you get a feel of the design details and colours of our products that appear on the Site as accurately as possible. However, what you actually see will depend on your monitor; we cannot guarantee that your monitor's display of any colour or other details will be accurate. </p>

<p>Electronic Communications</p>
<p>When you visit the Site or send emails to us, you are communicating with us electronically. You hereby provide your consent to receive communications from us electronically. We will communicate with you by email or by posting notices on the Site. You hereby agree that all notices, agreements and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing</p>. 
<p>Modification of Terms & Conditions of Service</p>
<p>littlefashion.in reserves the right to make changes to our Terms of Use and/or our Privacy Policy (which is incorporated herein by reference) at our sole discretion and you may not be notified. We suggest to you, therefore, that you re-read this important notice containing our Terms of Use and Privacy Policy from time to time in order that you stay informed as to any such changes. You have accepted the Agreement as amended if you continue to use any of littlefashion.in’s Services after any amendments are posted on our Website.</p>
 <a href=""> Top</a>
<p>Shop 'n' Earn Credit Points</p>
<p>Please read this program membership agreement ("Agreement") carefully before enrolling as a member of the Shop ‘n’ Earn Credit Points Program ("Program") This Agreement explains the terms and conditions that govern your participation in the Shop ‘n’ Earn Credit Points Program ("Program"). This Agreement is between you and BNJ LLP. It is your responsibility to read and understand the terms and conditions of this Agreement. By registering as a member in the Program ("Member"), you agree to be bound by these Program Terms of Use and littlefashion.in Privacy Policy.</p> 

<p>I.Program Overview</p>
<p>1. This is an online-only program designed to reward littlefashion.in customers for purchasing products from this site. The Program is available via access through the Program Websites only and cannot be used if buying products from 3rd party sites.</p>
<p>2. Participation in the Program and the benefits that are offered to Program members is at the sole discretion of BNJ LLP, and we have the right to change the respective Program terms and conditions, in whole or in part, at any time with or without giving any notice to its Members.</p>
<p>3. Program is available only to retail customers who are transacting on site, and would not be available to any wholesale/3rd party customers purchasing any littlefashion.in product(s). </p><br>

<p>II. Eligibility and Registration Requirements</p>
<p>1. You must be of legal age (18 years) to qualify for membership in the Program.</p>
<p>2. Members must be human: no machines, scripts, or automated services may be used to participate in this program. </p><br>


<p>III. Earning and Redeeming Rewards</p>
<p>1. You become a part of this program automatically on registering on littlefashion.in </p>
<p>2. We may introduce time-limited promotional offers ("Promotion") that enable Program Members to earn additional rewards for the completion of actions that are specified by us. </p>
<p>3. Once a Member meets all applicable requirements for a Promotion, the designated number of rewards specified by that Promotion shall be transferred to the Member. If eligible, the Credit Points would be credited to the users account within 48 hours of successful delivery of the order. Cancelled / Returned orders shall not add Credit Points to your account.</p> 
<p>4. If you choose to return/cancel part or whole of any order for which you have earned loyalty cash, BNJ may refund you a deducted amount basis the Loyalty Cash earned for the returned/cancelled product. Eg. If you return any product/products, priced at Rs. 500 which have earned you Rs.50 loyalty cash, BNJ holds the right to refund you only Rs. 450 to adjust for the Loyalty Cash earned by you. </p>
<p>5. BNJ is not responsible for changes to, or discontinuance of, any Promotion or for any effect on accrual of rewards caused by changes or discontinuance.</p> 
<p>6. At no point, can the earned Loyalty Cash be redeemed for cash. It may only be used to purchase products on littlefashion.in except in one condition where Guaranteed Savings Code is also used against the products in the order.</p> 
<p>7. The eligibility to use the Loyalty Cash against your purchased amount can be changed by BNJ LLP at any time during the program without prior intimation to the users.</p> 
<p>8. You will not earn any Credit Points in the following scenarios </p>
<p>a. If you have availed any offer which provides product(s) for free in your order</p>
<p>b. If you choose to earn Credit Points from any other 3rd party provider such as PAYBACK</p>
<p>9. Your Credit Points will be reduced by the percentage discount applicable on the product, either on site or through the use of any coupon code. Also the Credit Points applicable on the product at the time of purchase would be given to you. If the discounts are revised on a later date, you will not be entitled to the revised Credit Points. </p>
<p>10. If you return or cancel the order, you will not earn Credit Points against that order</p>
<p>11. If you return part of your order, you will only earn points for the products which have not been returned by you</p>
<p>12. BNJ  holds the right to decide which products earn you Credit Points and which do not. Additionally, it also holds the right to change the amount of Credit Points against any product without prior notice</p>
<p>13. Credit Points earned will expire by the 31st of March every year. Eg. All points earned for orders delivered between 1st April 2012 and 31st March 2013 will expire on 31st March 2013.</p><br>

<p>IV.Disclosure of Account Information</p>
<p>1. Any personal data (for example name, address, telephone number, or e-mail address) that you transmit through this site will be governed by littlefashion.in Privacy Policy, which is hereby incorporated by into these Terms and Conditions by reference.</p>
<p>2. You authorize BNJ LLP to disclose necessary information that you have provided to third parties, or information that BNJ LLP has obtained about your Account: (i) to agents of BNJ LLP or its affiliates, such as independent auditors, consultants or attorneys; (ii) to comply with government agency or court orders or requests; or (iii) where it is necessary for fulfillment with third party suppliers.</p>
<p>3. By entering into this Agreement, you authorize BNJ LLP and its Suppliers to share personal information about you, including but not limited to your e-mail address, full name and address. </p><br>


<p>V. Termination or Changes to the Program</p>
<p>1. BNJ LLP reserves the right to terminate the Program at any time without notice. Notification of Program termination by BNJ LLP would be publicized on the Program Web site only.</p>
<p>2. BNJ LLP may modify this Agreement from time to time, with or without notice, and your continued participation in the Program after such modification shall be deemed to be your acceptance of any such modification. It is your responsibility to check the Terms and Conditions page of the Program Website regularly to determine whether this Agreement has been modified. If you do not agree to any modification of this Agreement, you must immediately cease participation in the Program.</p><br>
 
<p>VI. Fraud; Termination of Membership</p>
<p>Membership in the Program is subject to the Program Terms and Conditions. Any failure to comply with the Program Terms and Conditions, any fraud or abuse relating to the accrual or redemption of rewards from BNJ LLP, or any misrepresentation of any information furnished to BNJ LLP or its affiliates by you, or anyone acting on your behalf, may result in the termination of your membership in the Program, cancellation of your Program account and/or forfeiture of your rewards / earnings. In the event of fraud, misconduct, or suspected fraud or misconduct by you or anyone acting on your behalf or under your password, BNJ LLP reserves the right to suspend access to your account indefinitely pending investigation</p><br>

 <a href=""> Top</a>
<p>Guaranteed Savings Program</p>
<p>Please read this program membership agreement ("Agreement") carefully before enrolling as a member of the Guaranteed Savings Program ("Program") This Agreement explains the terms and conditions that govern your participation in the Guaranteed Savings Program ("Program"). This Agreement is between you and BNJ LLP. It is your responsibility to read and understand the terms and conditions of this Agreement. By registering as a member in the Program ("Member"), you agree to be bound by these Program Terms of Use and littlefashion.in Privacy Policy. </p><br>

<p>I.Program Overview</p>
<p>1. This is an online-only program designed to reward littlefashion.in customers for purchasing products on this site. The Program is available via access through the Program Websites only and cannot be used if buying products from 3rd party sites.
</p>
<p>2. Participation in the Program and the benefits that are offered to Program members is at the sole discretion of BNJ LLP, and we have the right to change the respective Program terms and conditions, in whole or in part, at any time with or without giving any notice to its Members.</p>
<p>3. Program is available only to retail customers who are transacting on site, and would not be available to any wholesale/3rd party customers purchasing any littlefashion.in product(s).</p> <br>


<p>II. Eligibility and Registration Requirements</p>
<p>1. You must be of legal age (18 years) to qualify for membership in the Program.</p>
<p>2. Members must be human: no machines, scripts, or automated services may be used to participate in this program. </p><br>


<p>III. Buying & Redeeming Guaranteed Savings</p>
<p>Guaranteed Savings offer is limited to Brands, Subcategories or Products being displayed on the "Guaranteed Savings" page or in case if any special offer message being displayed against a particular product, brand & Subcategory item information pages on sites littlefashion.</p> 
<p>Once a Member meets all applicable requirements for a Promotion, the designated "Guaranteed Savings" code will be transferred to the Members email and to Members registered account with littlefashion.in.</p>
<p>Every "Guaranteed Savings" offer will carry validity & order criteria that need to be followed while placing order through Guaranteed Savings. Member can check these terms on https://www.littlefashion.in under the How it works and FAQ’s 
BNJ LLP is not responsible for changes to, or discontinuance of, any Promotion. </p>
<p>The eligibility to use the Guaranteed Savings code against specified Brand, Subcategories & Products changed by BNJ LLP at any time during the program without prior intimation to the users. </p>
<p>Member’s Subscription balance will be reduced once order is successfully placed with the "Guaranteed Savings" code. Additionally Usage, Validity and expiry of the "Subscription" can be checked under the member registered "My Account" section on littlefashion.in.</p> 
<p>Your participation in the Guaranteed Savings is personal to you, and you may not assign or transfer your Subscription or any of the benefits to any third party. </p>
<p>If any problems arise with your Guaranteed Savings offer, the usage disputes or offer expiry, validity associated with your Guaranteed Savings offer, we will either call or notify you via e-mail using the address associated with you asking you to help resolve the problem and reactivate your Guaranteed Savings offer.</p> 
<p>All returns under the "Guaranteed Savings" offers are subject to littlefashion.in "Return Policy" </p><br>


<p>IV.Payment and Renewal</p>
<p>Valid "Guaranteed Savings" offers can only be purchased through Online Payment Option, Gift Certificate, Credit Points and Cash Refund amount.</p>
<p>The total cost charged to you against the "Guaranteed Savings" code will be returned back to you in form of a "Guaranteed Savings" code which you can use anytime to buy subscription products and get minimum assured discount with every order placed.
Guaranteed Savings offer issued once cannot be renewed, member has to buy new offer in order to buy more products. </p><br>


<p>V. Offer usage with Offer/Promotional Codes</p>
<p>All cart offers/Offer/Promotional Code will work with the "Guaranteed Savings" code given that all the terms of use defined against the Cart Offers/Offer/Promotional code are met. Credit Points and Guaranteed Savings code cannot be used together in one order. </p><br>


<p>VI. Disclosure of Account Information</p>
<p>1. Any personal data (for example name, address, telephone number, or e-mail address) that you transmit through this site will be governed by littlefashion.in Privacy Policy, which is hereby incorporated by into these Terms and Conditions by reference.</p> 
<p>2. You authorize BNJ LLP to disclose necessary information that you have provided to third parties, or information that BNJ LLP has obtained about your Account: (i) to agents of BNJ LLP or its affiliates, such as independent auditors, consultants or attorneys; (ii) to comply with government agency or court orders or requests; or (iii) where it is necessary for fulfillment with third party suppliers. </p>
<p>3. By entering into this Agreement, you authorize BNJ LLP and its Suppliers to share personal information about you, including but not limited to your e-mail address, full name and address.</p><br>


<p>VII. Termination or Changes to the Program</p>
<p>1. BNJ LLP reserves the right to terminate the Program at any time without notice. Notification of Program termination by BNJ LLP would be publicized on the Program Web site only.</p>
<p>2. BNJ LLP may modify this Agreement from time to time, with or without notice, and your continued participation in the Program after such modification shall be deemed to be your acceptance of any such modification. It is your responsibility to check the Terms and Conditions page of the Program Website regularly to determine whether this Agreement has been modified. If you do not agree to any modification of this Agreement, you must immediately cease participation in the Program.</p><br>

<a href=""> Top</a><br>

<p>Other Terms</p>
<p>Reviews, Feedback, Submissions</p>
<p>End User acknowledges that all discussion for ratings, comments, bulletin board service, chat rooms and/or other message or communication facilities (collectively "Communities") are public and not private communications. littlefashion.in does not control or endorse the content, messages or information found in any Community, and, therefore, littlefashion.in specifically disclaims any liability concerning the Communities and any actions resulting from End Users participation in any Community, including any objectionable content. Generally, any communication which End User posts to littlefashion.in (whether in chat rooms, discussion groups, message boards or otherwise) is considered to be non-confidential. If particular web pages permit the submission of communications that will be treated by littlefashion.in as confidential, that fact will be stated on those pages. By posting comments, messages or other information on the Site, End User grants littlefashion.in the right to use such comments, messages or information for promotions, advertising, market research or any other lawful purpose.</p><br>
 

<p>Copyright & Trademark</p>
<p>Everything located on or in this Site, including the Microsites, is our exclusive property and can be used with express permission of the copyright and/or trademark owner. ANY COPYING, DISTRIBUTING, TRANSMITTING, POSTING, LINKING, DEEP LINKING, OR OTHERWISE MODIFYING OF THIS SITE OR ANY OF THE MICROSITES WITHOUT OUR EXPRESS WRITTEN PERMISSION OF littlefashion.in IS STRICTLY PROHIBITED. Any violation of this policy may result in a copyright, trademark or other intellectual property right infringement that may subject End User to civil and / or criminal penalties.</p> 
<p>This Site and Microsites contains copyrighted material, trademarks and other proprietary information, including, but not limited to, text, software, photos, video, graphics, music, sound, and the entire contents of website protected by copyright. We own a copyright in the selection, coordination, arrangement and enhancement of such content, as well as in the content original to it. End User may not modify, publish, transmit, participate in the transfer or sale, create derivative works, or in any way exploit, any of the content, in whole or in part. End User may download / print / save copyrighted material for End User's personal use only. Except as otherwise expressly stated under copyright law, no copying, redistribution, retransmission, publication or commercial exploitation of downloaded material without our express permission of littlefashion.in and the copyright owner is permitted. If copying, redistribution or publication of copyrighted material is permitted, no changes in or deletion of author attribution, trademark legend or copyright notice shall be made. End User acknowledges that he/she/it does not acquire any ownership rights by downloading copyrighted material. Trademarks that are located within or on the Site or a Web site otherwise owned or operated in conjunction with littlefashion.in shall not be deemed to be in the public domain but rather the exclusive property of owners, unless such site is under license from the Trademark owner thereof in which case such license is for the exclusive benefit and use of littlefashion.in, unless otherwise stated. </p>
<p>End User shall not upload, post or otherwise make available on this Site any material protected by copyright, trademark or other proprietary right without the express permission of the owner of the copyright, trademark or other proprietary right. We do not have any express burden or responsibility to provide End User with indications, markings or anything else that may aid End User in determining whether the material in question is copyrighted or trademarked. End User shall be solely liable for any damage resulting from any infringement of copyrights, trademarks, proprietary rights or any other harm resulting from such a submission. By submitting material to any public area of this Site, End User warrants that the owner of such material has expressly granted us the royalty-free, perpetual, irrevocable, non-exclusive right and license to use, reproduce, modify, adapt, publish, translate and distribute such material (in whole or in part) worldwide and/or to incorporate it in other works in any form, media or technology now known or hereafter developed for the full term of any copyright that may exist in such material. End User also permits any other end user to access, view, store or reproduce the material for that end user's personal use. End User hereby grants us the right to edit, copy, publish and distribute any material made available on this Site by End User. We hereby reserves the right to terminate its agreement with any End User who repeatedly infringes on copyright rights upon notification to us by the copyright owner. </p>
<p>The foregoing provisions of this clause apply equally to and are for the benefit of littlefashion.in, its subsidiaries, affiliates and its third party content providers and licensors and each shall have the right to assert and enforce such provisions directly or on its own behalf.</p><br>
 

<p>Indemnity</p>
<p>You agree to defend, indemnify and hold harmless BNJ LLP, its employees, directors, officers, agents and their successors and assigns from and against any and all claims, liabilities, damages, losses, costs and expenses, including attorney's fees, caused by or arising out of claims based upon your actions or inactions, which may result in any loss or liability to us or any third party including but not limited to breach of any warranties, representations or undertakings or in relation to the non-fulfillment of any of your obligations under this User Agreement or arising out of the your violation of any applicable laws, regulations including but not limited to Intellectual Property Rights, payment of statutory dues and taxes, claim of libel, defamation, violation of rights of privacy or publicity, loss of service by other subscribers and infringement of intellectual property or other rights. This clause shall survive the expiry or termination of this User Agreement.</p> <br>


<p>Termination</p>
<p>We may terminate this Agreement at any time. Without limiting the foregoing, we shall have the right to terminate any passwords or accounts of End User in the event of any conduct by End User which we, in our sole discretion, consider to be unacceptable, or in the event of any breach by End User of this Agreement. Our right to any Comments shall survive any termination of this User Agreement. Any such termination of the User Agreement shall not cancel your obligation to pay for the product already ordered from the Site or affect any liability that may have arisen under the User Agreement. </p><br>


<p>Limitation of Liability and Disclaimers</p>
<p>The Site is provided without any warranties or guarantees and in an "As Is" condition. You must bear the risks associated with the use of the Site.</p>
<p>The Site provides content from other Internet sites or resources and while we try to ensure that material included on the website is correct, reputable and of high quality, it cannot accept responsibility if this is not the case. We will not be responsible for any errors or omissions or for the results obtained from the use of such information or for any technical problems you may experience with the Site.</p>
<p>This disclaimer does not apply to any product warranty offered by the manufacturer of the product as specified in the product specifications. This disclaimer constitutes an essential part of this User Agreement. To the fullest extent permitted under applicable law, we or our suppliers shall not be liable for any indirect, incidental, special, incidental, consequential or exemplary damages, including but not limited to, damages for loss of profits, goodwill, use, data or other intangible losses arising out of or in connection with the Site, its services or this User Agreement. </p>
<p>Without prejudice to the generality of the section above, the total liability of littlefashion.in to you for all liabilities arising out of this User Agreement be it in tort or contract is limited to the value of the product ordered by you. BNJ LLP, their associates and technology partners make no representations or warranties about the accuracy, reliability, completeness, currentness and/or timeliness of any content, information, software, text, graphics, links or communications provided on or through the use of the Site or that the operation of the Site will be error free and/or uninterrupted. Consequently, we assume no liability whatsoever for any monetary or other damage suffered by you on account of the delay, failure, interruption, or corruption of any data or other information transmitted in connection with use of the Site; and/or any interruption or errors in the operation of the Site. </p><br>


<p>Site Security</p>
<p>You are prohibited from violating or attempting to violate the security of the Site, including, without limitation, (a) accessing data not intended for you or logging onto a server or an account which you are not authorized to access; (b) attempting to probe, scan or test the vulnerability of a system or network or to breach security or authentication measures without proper authorization; (c) attempting to interfere with service to any other user, host or network, including, without limitation, via means of submitting a virus to the Site, overloading, "flooding," "spamming," "mail bombing" or "crashing;" (d) sending unsolicited email, including promotions and/or advertising of products or services; or (e) forging any TCP/IP packet header or any part of the header information in any email or newsgroup posting. Violations of system or network security may result in civil or criminal liability. littlefashion.in will investigate occurrences that may involve such violations and may involve, and cooperate with, law enforcement authorities in prosecuting users who are involved in such violations. You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of this Site or any activity being conducted on this Site. You agree, further, not to use or attempt to use any engine, software, tool, agent or other device or mechanism (including without limitation browsers, spiders, robots, avatars or intelligent agents) to navigate or search this Site other than the search engine and search agents available from littlefashion.in on this Site and other than generally available third party web browsers (e.g., Netscape Navigator, Microsoft Explorer). </p><br>


<h3>MISCELLANEOUS</h3>
<p>1. Force Majeure: Without prejudice to any other provision herein, we will not be liable for any loss, damage or penalty as a result of any delay in or failure to deliver or otherwise perform hereunder due to any cause beyond the our control, including, without limitation, acts of the End User, embargo or other governmental act, regulation or request affecting the conduct of littlefashion.in 's business, fire, explosion, accident, theft, vandalism, riot, acts of war, strikes or other labor difficulties, lightning, flood, windstorm or other acts of God. </p>
<p>2. Entire Agreement: This Agreement and any operating rules for the Website established by littlefashion.in constitute the entire agreement of the parties with respect to the subject matter hereof. 
3. Waiver: No waiver by either party of any breach or default hereunder is a waiver of any preceding or subsequent breach or default. The failure of either party to exercise any of its rights under this Agreement shall not be deemed a waiver or forfeiture of such rights or any other rights provided hereunder.</p> 
<p>4. Headings: The section headings used herein are for convenience only and shall be of no legal force or effect. </p>
<p>5. Severability: If any provision of this Agreement is held invalid by a court of competent jurisdiction, such invalidity shall not affect the enforceability of any other provisions contained in this Agreement and the remaining portions of this Agreement shall continue in full force and effect. </p>
<p>6. Governing Law: This Agreement will be governed by laws of India, subject to the Courts in Pune, without reference to conflict of laws principles, if any. </p>
<p>7. Payment Decline: We as a merchant shall be under no liability whatsoever in respect of any loss or damage arising directly or indirectly out of the decline of authorization for any Transaction, on Account of the Cardholder having exceeded the preset limit mutually agreed by us with our acquiring bank from time to time.</p>
                </div>
                </div>
			</div>
		</section>
		<!-- END PRODUCT GRID -->

		<!-- PARTNER -->
		<!-- END PARTNER -->

		<!-- FOOTER -->
		<footer class="dark">
        	<?php include_once('footer.php');?>
		</footer>
		<!-- END FOOTER -->

		<!-- SCROLL TOP -->
		<div id="scroll-top" class="_1">Scroll Top</div>
		<!-- END SCROLL TOP -->

	</div>

	<!-- Library JS -->
	<script src="js/library/jquery-1.11.0.min.js" type="text/javascript"></script>
	<script src="js/library/jquery-ui.min.js" type="text/javascript"></script>
	<script src="js/library/bootstrap.min.js" type="text/javascript"></script>
	<script src="js/library/owl.carousel.min.js" type="text/javascript"></script>
	<script src="js/library/jquery.ui.touch-punch.min.js" type="text/javascript"></script>
	<script src="js/library/parallax.min.js" type="text/javascript"></script>
	<script src="js/library/jquery.countdown.min.js" type="text/javascript"></script>
	<script src="js/library/jquery.mb.YTPlayer.js" type="text/javascript"></script>
	<script src="js/library/jquery.responsiveTabs.min.js" type="text/javascript"></script>
	<script src="js/library/jquery.fancybox.js" type="text/javascript"></script>
	<script src="js/library/SmoothScroll.js" type="text/javascript"></script>
	<script src="js/library/isotope.min.js" type="text/javascript"></script>
	<script src="js/library/jquery.colio.min.js" type="text/javascript"></script>

	<!-- Main Js -->
	<script src="js/script.js" type="text/javascript"></script>
         <script src="//code.jquery.com/ui/1.11.3/jquery-ui.js"></script>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

   <script src="js/auto-product.js"></script>
    
</body>
</html>